### PR TITLE
Add license file to v1.3

### PR DESCRIPTION
**Pull request by patricksmms**
Ref #114

This version needs to be published to npm as `postcss-modules-values@1.3.1`. @evilebottnawi, can you help with it, so then it can be updated on `css-loader`?

### CODE REVIEW

**Comment by patricksmms** [comment]
Oops, I added the text of MIT, but the version 1.3 was ISC. Will update.

**Comment by alexander-akait** [comment]
Need also push in this branch https://github.com/css-modules/postcss-icss-values/tree/v1.3.0

**Comment by alexander-akait** [comment]
Sorry not right link , i create branch https://github.com/css-modules/postcss-icss-values/tree/version-1, heck checkout on `version-1` branch, add License and send a PR too and we can update this in `css-loader`

**Comment by patricksmms** [comment]
OK

**Pull request closed without merging**
